"""
curriculum/seed/export_sql.py — emit deterministic SQLite INSERT statements
---------------------------------------------------------------------------
Reads grade2_math_counting.json and produces seed.sql (INSERTs) that, combined
with schemas/schema.sql, fully populate the Room database offline. Deterministic:
stable ordering, no LLM, no randomness.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SEED = os.path.join(HERE, "grade2_math_counting.json")
OUT = os.path.join(HERE, "seed.sql")

_TABLE_ORDER = [
    "grades", "subjects", "chapters", "lessons", "learning_outcomes",
    "teacher_instructions", "activities", "assessments", "vocabulary_terms",
    "flashcard_concepts",
]


def _sql(val):
    if val is None:
        return "NULL"
    s = str(val).replace("'", "''")
    return "'" + s + "'"


def main():
    with open(SEED, "r", encoding="utf-8") as f:
        data = json.load(f)
    lines = ["-- Vachak curriculum seed INSERTs (generated by export_sql.py; deterministic)",
             "-- Apply AFTER schemas/schema.sql", ""]
    for table in _TABLE_ORDER:
        rows = data.get(table, [])
        if not rows:
            continue
        cols = list(rows[0].keys())
        lines.append(f"-- {len(rows)} row(s) into {table}")
        for r in rows:
            vals = ", ".join(_sql(r.get(c)) for c in cols)
            lines.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({vals});")
        lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote", OUT, "with", sum(len(data.get(t, [])) for t in _TABLE_ORDER), "rows")


if __name__ == "__main__":
    main()
